name: Docker Image - Website (Production)

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: build
    - uses: actions/setup-node@v1
      with:
        node-version: 16
        registry-url: https://npm.pkg.github.com/
        scope: "@anyways-open"
    - name: npmrcgen
      run: |
        cd build
        echo "registry=https://registry.npmjs.org/" > .npmrc
        echo "@{anyways-open}:registry=https://npm.pkg.github.com/" >> .npmrc
        echo "anyways-open/url-hash:registry=https://registry.npmjs.org/" >> .npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_SECRET }}" >> .npmrc

    - name: checkout deployment repo
      uses: actions/checkout@v4    
      with:
        repository: 'anyways-open/functional-routeplanner-ovl-deployed'
        path: deployment
        ref: main
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: To handle 'not get uid/gid'
      run: cd build && npm config set unsafe-perm true
    - name: install packages
      run: cd build && npm ci      
    - name: Build
      env:
        NODE_OPTIONS: "--max_old_space_size=4096"
      run: cd build && npm run build
      
    - run: cd ./deployment && rm -R *
    - run: cd ./build/public/ && cp -R * ../../deployment/
    - run: |
        # Note: the following account information will not work on GHES
        cd ./deployment 
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "generated"
        git push
